### ISSUE TITLE
doesn't install with Package Manager on ST3

### ISSUE THREAD

**Issue by soenkekluth** [Pleasurazy/Sublime-Better-Completion#15]
download or clone woks.

**Comment by wayferer** [comment]
I just installed this in ST3 via Package Control and had to copy settings from its default to user and enable the completions that I wanted and then restart ST3 for it to start working.

**Comment by Pleasurazy** [comment]
@wayferer is right.

I am create a new User on my OS X 10.10.2 for test Package Control Installation.

It was work.

Installation Readme is updated. Readme now should be better.

Please check it.

![image](https://cloud.githubusercontent.com/assets/1500206/6395903/4b4701fc-be16-11e4-85a5-adc2f042e7ab.png)

I am Sorry for readme missing explain.
