### ISSUE TITLE
Confused as to placement of the file

### ISSUE THREAD

**Issue by ElektroDesigns** [Pleasurazy/Sublime-Better-Completion#22]
Hello! hope your well! Im trying to get the better-completion for Bootstrap to work, however when i place the setting file into Packages<User and then restart sublime nothing happens when i type bootstrap commands,absolutely no auto completion comes up for any bootstrap term. Seems as if i followed the directions correctly but could be mistaken. Thank you.

**Comment by ctf0** [comment]
@ElektroDesigns u need to include the name of the file inside ur user settings file
ex.`sbc-api-Words.sublime-settings` u should add this to the settings file `sbc-setting.sublime-settings` 

``` js
"completion_active_list": {
    // everything else

    "Words": true,
}
```
