### ISSUE TITLE
Is this plugin working with Ubuntu 14.01 in st2 ?

### ISSUE THREAD

**Issue by yashvekaria** [Pleasurazy/Sublime-Better-Completion#28]
I have install this plugin and enabled html and bootstrap apis for auto completion. So as it is tested under mac os X and windows 7 & 8. Is it working ubuntu 14.04 ?

**Comment by Pleasurazy** [comment]
I am not ubuntu user.

But I think Sublime Text is a cross platform app and it using Python.

Should be work.
