### ISSUE TITLE
Trailing comma causes parse error

### ISSUE THREAD

**Issue by p3k** [Pleasurazy/Sublime-Better-Completion#29]
I am getting the following error when starting up Sublime Text 2.0.2, Build 2221:

> Error trying to parse settings: Trailing comma before closing bracket in ~/.config/sublime-text-2/Packages/Better Completion/sublime-completions/sbc-api-sql.sublime-settings:654:3

If I remove the comma in the file and line mentioned the error is gone.

My version of Sublime-Better-Completion is 1.4.1.

**Comment by Pleasurazy** [comment]
Thank you!
